### ISSUE TITLE
ovh.exceptions.APIError: Internal server error on vps/use api

### ISSUE THREAD

**Issue by sukhpalhub** [ovh/python-ovh#122] opened 2023-05-20 08:20 UTC
I am getting server error on the following route for trying to find the memory usage for the vps:

```
client = ovh.Client()
params = {'type': 'mem:used'}
result = client.get("/vps/{server-name}/use", True, **params)
```

response:
```
ovh.exceptions.APIError: Internal server error 
OVH-Query-ID: CA.ext-5.6468811b.18216.a9ba91f3-57a2-499f-91e7-9c57547fbd49
```

Also,
/vps/{serviceName}/statistics does not work either to get memory usage.  

/vps route works fine and return the vps information so my connection is working fine and it's the issue with the route.
Same error displays when using from the console preview for these routes: https://ca.api.ovh.com/console-preview

**Comment by rbeuque74** [comment] 2023-05-24 08:27
Hello @sukhpalhub ,

Thanks for your issue.
We investigated your issue, and it looks like the problem comes from the OVHcloud API that returns the Internal Server Error.
VPS team here at OVHcloud has been warned about the issue.

Regarding your GitHub issue, as the problem is not related to the `python-ovh` wrapper, I will close this issue, and let you follow the resolution of your issue on our customer mailing-list, `api@ml.ovh.net` .

Feel free to open a new issue if you have a specific issue with `python-ovh`, or subscribe&send an email on our mailing-list if you spot issue on the API itself.

Thanks
Romain

**Closed by rbeuque74** 2023-05-24 08:27 UTC
