### ISSUE TITLE
integrating with flask doesn't find ovh.conf

### ISSUE THREAD

**Issue by seccentral** [ovh/python-ovh#9] opened 2015-06-08 11:47 UTC
Hello, 

When i try to integrate this with flask what exactly do i need to do to include the ovh.conf ?
It never seems to find it, even if it resides in the current directory as my .py flask file.
*** I am working on windows using pycharm ***

**Comment by yadutaf** [comment] 2015-06-08 21:23
Hi,

Thanks for taking the time to report this bug. To help troubleshoot it, can you give detailed steps to reproduce this bugs including a code sample? Do you still experience this issue without flask, maybe using one of the provides examples?

If it still fails, this may be caused by the hardcoded ``/`` instead of ``\`` when running windows in https://github.com/ovh/python-ovh/blob/master/ovh/config.py#L77.  Can you by any chance test it on your side?

Thanks,

**Comment by seccentral** [comment] 2015-06-09 08:05
For instance.
Take this apitraining.py file: 
http://pastebin.com/YS5hqNRV
in the same dir as apitraining.py i have a properly configured ovh.conf 
when i run apitraining.py i get this error:
http://pastebin.com/48LsjguL
the ovh.conf looks like this : 
http://pastebin.com/KzgQTFWu

This happens when i use the ide.
From a command line it's the same.
i

**Comment by LukeMarlin** [comment] 2015-06-09 20:30
Just tested with your apitraining.py file and the example conf of the repo, and everything runs fine.
Remember that the working directory is the place where your console runs, not where your actual Python program lays.

For instance, when I spawn a fresh `cmd` and run the `python <some directories>\apitraining.py` it will fail. If however you first `cd <some directories>` and then run `python apitraining.py` everything will work as expected. As a side note, simply double clicking the apitraining.py worked perfectly as well on my side.

**Comment by yadutaf** [comment] 2015-06-10 12:47
@LukeMarlin Thanks for triaging this issue. As it does not appear to be an actual bug, I'll close this issue for now. @seccentral Feel free to re-open this issue if you believe this is a real bug.

**Closed by yadutaf** 2015-06-10 12:47 UTC
